#Override containers for ovh environments
version: "2.4"
services:
  reverse_proxy:
    ports:
      - 443:443
    volumes:
      - /opt/flux-retour-cfas/data/nginx:/data
      - /opt/flux-retour-cfas/data/ssl:/ssl:ro
      - /opt/flux-retour-cfas/.overrides/reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /opt/flux-retour-cfas/.overrides/reverse_proxy/maintenance_ips.conf:/etc/nginx/conf.d/maintenance_ips.conf:ro

  ui:
    command: yarn serve

  server:
    environment:
      - FLUX_RETOUR_CFAS_MNA_REFERENTIEL_ENDPOINT_URL=https://referentiel.apprentissage.onisep.fr/api/v1
      - FLUX_RETOUR_CFAS_CLAMAV_URI=clamav:3310
    volumes:
      - /opt/flux-retour-cfas/data/server:/data

  mongodb:
    volumes:
      - /opt/flux-retour-cfas/data/mongodb/db:/data/db
      - /opt/flux-retour-cfas/data/mongodb/configdb:/data/configdb
      - /opt/flux-retour-cfas/data/mongodb/backups:/data/backups-legacy
      - /opt/flux-retour-cfas/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  redis:
    volumes:
      - /opt/flux-retour-cfas/data/redis:/data

  metabase:
    image: metabase/metabase:v0.44.4
    container_name: flux_retour_cfas_metabase
    volumes:
      - /opt/flux-retour-cfas/data/metabase:/metabase-data
    depends_on:
      - mongodb
    environment:
      JAVA_TIMEZONE: Europe/Paris
      MB_DB_FILE: /metabase-data/metabase.db
      MB_SITE_LOCALE: fr
      MB_SITE_URL: http://0.0.0.0/metabase
    restart: always
    networks:
      - flux_retour_cfas_network
