# Worflow pour CI sur le server
name: Server - Install, lint, test

on: [push]

jobs:
  # Single job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the repository
      - uses: actions/checkout@v2

      # define node version to use, otherwise Github Actions will use the one shipped with ubuntu-latest (https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#language-and-runtime)
      - name: Use Node.js 16.6.0
        uses: actions/setup-node@v2
        with:
          node-version: '16.6.0'

      # Install dependencies
      - name: Run Yarn Install
        run: |
          cd server
          yarn install --frozen-lockfile

      # Lint
      - name: Run Lint
        run: |
          cd server
          yarn lint

      # Start dockers containers
      - name: Start Docker
        run: |
          cd server
          yarn docker:start

      # Run mocha tests
      - name: Run Tests
        run: |
          cd server
          docker exec flux_retour_cfas_server bash -c "yarn test"
